# Generated by Django 3.1.4 on 2020-12-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='supervision',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
