# Generated by Django 3.1.4 on 2020-12-18 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_supervision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day_ticket_limit',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(200)]),
        ),
    ]
