# Generated by Django 3.1.4 on 2020-12-20 22:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20201218_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=27),
            preserve_default=False,
        ),
    ]
